# Generated by Django 5.0.6 on 2024-07-05 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankedaccount',
            name='image',
            field=models.ImageField(null=True, upload_to='ranked_accounts/'),
        ),
    ]
