# Generated by Django 5.0.6 on 2024-07-05 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rankedaccount_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankedaccount',
            name='image',
            field=models.ImageField(blank=True, default='shop/img/default.jpg', upload_to='ranked_accounts/'),
        ),
    ]
