# Generated by Django 5.0.6 on 2024-07-05 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_rankedaccount_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rankedaccount',
            name='image',
        ),
        migrations.AddField(
            model_name='rankedaccount',
            name='default_image_url',
            field=models.URLField(default='https://image0.uhdpaper.com/wallpaper-hd/rengar-lol-headhunter-splash-art-uhdpaper.com-hd-583.jpg'),
        ),
    ]
