# Generated by Django 5.0.6 on 2024-07-05 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_rankedaccount_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rankedaccount',
            name='default_image_url',
        ),
        migrations.AddField(
            model_name='rankedaccount',
            name='image',
            field=models.ImageField(null=True, upload_to='ranked_accounts/'),
        ),
    ]
