# Generated by Django 5.0.6 on 2024-07-05 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_rankedaccount_default_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankedaccount',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ranked_accounts/'),
        ),
    ]
