# Generated by Django 5.0.6 on 2024-07-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_comuna_contactform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankedaccount',
            name='price',
            field=models.IntegerField(),
        ),
    ]
